### ISSUE TITLE
Matheus me ajuda com o fronts 🤯

### ISSUE THREAD

**Issue by JoaoRodriguesRD** [JoaoRodriguesRD/flutter-pix-tecnology#1]

**Comment by JoaoRodriguesRD** [comment]
vou resolver 🤭

**Comment by Mathewsmag** [comment]
Cheguei 😘

**Comment by JoaoRodriguesRD** [comment]
🤓bababoy!

**Comment by Mathewsmag** [comment]
Ueeeeppppaaaa

**Comment by Mathewsmag** [comment]
Cavalo

**Comment by Mathewsmag** [comment]
![8588913d00587cb29e6c9c488cbb5f61a4dfa0ebeec1821529a2820beae16864_1 jpg](https://user-images.githubusercontent.com/53982706/175128670-03764216-4295-4ac0-9ea0-80b2601528ed.jpg)

**Comment by Mathewsmag** [comment]
![7c7384cda0055faf7acb69e00cd44372eac263eb5d180091e767f0c37835cb89_1 jpg](https://user-images.githubusercontent.com/53982706/175128938-43b593a9-b488-4974-b501-33fdfb955104.jpg)

**Comment by Mathewsmag** [comment]
![12f368fdb2b90e3df1484f8e86dd5fc55ae684ce505cf4ad462d1ed58fa78b28_1 jpg](https://user-images.githubusercontent.com/53982706/175129011-a0298f64-9f0a-4cab-ad7d-f258cd21d785.jpg)

**Comment by Mathewsmag** [comment]
![67ad1fe85244dfaede96e1b726317ad33e67cbb4379ba92e075341e1fb68663c_1 jpg](https://user-images.githubusercontent.com/53982706/175129046-7166a30f-eebe-4aa3-a1a7-6cac5c0b23d0.jpg)

**Comment by Mathewsmag** [comment]
![4a606788a785532da9b31b418006ec702ac6a1821f595ac92a3c1b3b981d5bca_1 jpg (1)](https://user-images.githubusercontent.com/53982706/175129286-ff12f217-612f-4dca-92c2-c230e1d82b83.jpg)

**Comment by Mathewsmag** [comment]
@JoaoRodriguesRD

**Comment by Mathewsmag** [comment]
![7d21023410d44bb6ee625fbd261640a72ab070f49435e9138c74c76f8af68fba_1 jpg](https://user-images.githubusercontent.com/53982706/175130537-b85545b7-c234-443d-bba2-d08057becff5.jpg)

**Comment by Mathewsmag** [comment]
![bf6f8af784fdd399554edc70b636384acca334bd7daf7a7ea4585b7fa84c5432_1 jpg](https://user-images.githubusercontent.com/53982706/175130621-a0b739d2-ba8f-43e3-a674-85cb9f17a218.jpg)

**Comment by Mathewsmag** [comment]
![0275d245bdca242bee36a8e2c52a10665fa86c0102cd72012e3dc29e5d44748e_1 jpg](https://user-images.githubusercontent.com/53982706/175130672-9a5965f5-fda2-4ef0-9a5b-f27d7c7a706c.jpg)

**Comment by Mathewsmag** [comment]
![3de9cd4bad061f506d10aead1c719c8cda8e8f25d73151a1e0c1caa174d3a5fa_1 jpg](https://user-images.githubusercontent.com/53982706/175132310-71f32569-e4d2-4c8a-b411-d557a1e711ae.jpg)
![78628c09bc27fbeced13f86c47ead57c5db65a70924f50c50075cbe1d8ab5bdd_1 jpg](https://user-images.githubusercontent.com/53982706/175132314-9cd76956-c01a-48d0-bac7-15863e5073aa.jpg)
![c39ad79886847d55ce6c5f4b7b5f333c354e7c9e6d92d8705ca1baf3e76d4348_1 jpg](https://user-images.githubusercontent.com/53982706/175132318-14c61d64-20a8-4e6a-aa79-0c25dad984f2.jpg)
![9e38db59276f8d296f27e3e368dd51cf6b79a66b02fbeb8e2c0f98fd08e3742c_1 jpg](https://user-images.githubusercontent.com/53982706/175132321-c0f81091-618e-4e9f-8b8e-c21c26a62072.jpg)
![772a07abb3ace81b3fe63f401228717b5a9f260ea8cac9a9a8242dddb6fe0cae_1 jpg](https://user-images.githubusercontent.com/53982706/175132326-240cae4e-18b1-4627-9904-d51d27f690c4.jpg)
![359f9b2f9c025b45aabc36693044fdfcc6cd6a46b90c0f4588f2a181f1da520e_1 jpg](https://user-images.githubusercontent.com/53982706/175132327-334538a8-4334-478a-9f4e-ef2aa626e444.jpg)
![a056ac919144a6a5448c8f973107b2f6c1945e3a6c50bfa45c85c4e169f6b481_1 jpg](https://user-images.githubusercontent.com/53982706/175132330-51203d00-e4d6-4e46-a784-de042fd01203.jpg)
![db57ecbccdbdc9f00e077375de67971c5e50f90bbf55b125be7c8e4beb711b13_1 jpg](https://user-images.githubusercontent.com/53982706/175132333-dfe029d1-8ac5-4f79-a842-7378f64bc175.jpg)
![1e2c5fa04d71299454a5fb7a21e36cf8e034ce5055b2b152800d09ff0d3ad06b_1 jpg](https://user-images.githubusercontent.com/53982706/175132336-329dca47-edbc-4707-935e-78dc3f3a0b67.jpg)
![06adae4ea916ea300d2e98d80598ac1d9a3220ad1d032242e891e3f2c3ce3e34_1 jpg](https://user-images.githubusercontent.com/53982706/175132338-f9dc8f30-7782-460c-a889-6bfeb14bebfa.jpg)
![4d5d71132c7a3de69e811027bd449280b47dfd511fabc5060ed0a9897b2b9ac5_1 jpg](https://user-images.githubusercontent.com/53982706/175132343-122faf13-1cdd-4eea-9f2a-c17c104c7956.jpg)
![3389cb2b95189bab7a9e73bfd84d83559c6f6f21d4895c6a1805e629a32038b6_1 jpg](https://user-images.githubusercontent.com/53982706/175132346-1339ede7-d9e2-4283-b1b5-968dfede2e41.jpg)
![e464cda191087454eda719b845669ed188e18f1ad4f132d678fe5ec43614dc30_1 jpg](https://user-images.githubusercontent.com/53982706/175132348-8280a347-b81a-40cf-a303-a9f9807706d0.jpg)
![6f9fa369aa97d4f0b606a531252af261b7a46545496ed731724eda5053683d92_1 jpg](https://user-images.githubusercontent.com/53982706/175132351-26647ce9-0fdb-4de3-9749-84ad5a727d1e.jpg)
![ad1330bce3813d4b8b91909cf55bc7efbe2bd0b19ec013b5f07955448b101cd7_1 jpg](https://user-images.githubusercontent.com/53982706/175132353-ad4c91a5-d58a-4bbf-bd01-cdac928dac1e.jpg)
![1df21b365caf5107235bcb9af925be56edc66a322de2d1dd931e5aab3611c786_1 jpg](https://user-images.githubusercontent.com/53982706/175132357-6db14673-f62a-40a4-b884-e67c49b967e6.jpg)
![d908eff4accb9c783ab91ee05ff018c921a954f5a606a21041338efeaa6776f7_1 jpg](https://user-images.githubusercontent.com/53982706/175132359-19d6d38c-cf87-4713-a3db-5954f400e3cc.jpg)
![6cf3331684cdc99bd8a787bc2350503e3e0068f89f3e121b8b30e3f6d5009a84_1 jpg](https://user-images.githubusercontent.com/53982706/175132362-88053031-9d95-4462-80a4-9c6654aeac81.jpg)
![70617c3b0034f856cd44b8576442baac9283c5b60e1f8a088f810a903412b7ad_1 jpg](https://user-images.githubusercontent.com/53982706/175132364-dadbeae4-7856-41a8-bf3c-629c104f0585.jpg)
